artifacts_root: artifacts


# live_weather_data_ingestion:
#   root_dir: artifacts/01_raw
#   base_url: https://api.openweathermap.org/data/3.0/onecall/timemachine
#   base_url_forecast: https://api.openweathermap.org/data/3.0/onecall
#   local_data_file: artifacts/01_raw/live_weather.json
#   hours_of_history: 4
#   secret_info: config/secret_keys.yaml


# live_weather_data_transformation:
#   root_dir: artifacts/02_intermediate
#   input_file: artifacts/01_raw/live_weather.json
#   output_file_forecast: artifacts/02_intermediate/live_weather_forecast.pickle
#   output_file_actuals: artifacts/02_intermediate/live_weather_actuals.pickle
#   hours_of_forecast: 48

open_metro_API:
  root_dir: artifacts/02_intermediate
  latitude: 50.80043
  longitude: -1.976201
  features_minutely_15: 
    - temperature_2m
    - relative_humidity_2m
    - dew_point_2m
    - apparent_temperature
    - precipitation
    - rain
    - snowfall
    - snowfall_height
    - freezing_level_height
    - sunshine_duration
    - weather_code
    - wind_speed_10m
    - wind_speed_80m
    - wind_direction_10m
    - wind_direction_80m
    - wind_gusts_10m
    - visibility
    - cape
    - lightning_potential
    - is_day
    - shortwave_radiation
    - direct_radiation
    - diffuse_radiation
    - direct_normal_irradiance
    - global_tilted_irradiance
    - terrestrial_radiation
    - shortwave_radiation_instant
    - direct_radiation_instant
    - diffuse_radiation_instant
    - direct_normal_irradiance_instant
    - global_tilted_irradiance_instant
    - terrestrial_radiation_instant
  features_hourly: 
    - cloud_cover 
    - cloud_cover_low
    - cloud_cover_mid
    - cloud_cover_high

open_metro_hitorical:
  local_data_file_15minutely: artifacts/02_intermediate/historical_15minutely_data.pickle
  local_data_file_hourly: artifacts/02_intermediate/historical_hourly_data.pickle
  start_date: "2023-04-02"
  end_date: "2024-09-06"

open_metro_forecast: 
 local_data_file_15minutely: artifacts/02_intermediate/forecast_15minutely_data.pickle
 local_data_file_hourly: artifacts/02_intermediate/forecast_hourly_data.pickle
 past_days: 3
 forecast_days: 7


solis_data_ingestion:
  root_dir: artifacts/01_raw
  # output_file: artifacts/01_raw/solis.json 
  output_file_training: artifacts/01_raw/solis_historical.pickle
  training_start_date: "04/02/2023" # "04/02/2023"
  training_end_date: "09/06/2024" # "14/08/2024"
  output_file_today: artifacts/01_raw/solis_today.pickle
  url: 'https://www.soliscloud.com:13333'
  VERB: "POST"
  string_format: '%a, %d %b %Y %H:%M:%S GMT'
  encoder: 'utf-8'
  Content_Type: "application/json"
  CanonicalizedResource: "/v1/api/inverterDay"

training_data_preparation:
 root_dir: artifacts/03_features
 input_data_15minutely: artifacts/02_intermediate/historical_15minutely_data.pickle
 input_data_hourly: artifacts/02_intermediate/historical_hourly_data.pickle
 input_solis: artifacts/01_raw/solis_historical.pickle 
 output_file_train: artifacts/03_features/historical_training_data.pickle
 target_var: pac
 resample: 1h
 laggTime: [1,2,3]
 lagged_features:
    - direct_normal_irradiance
    - direct_radiation_instant
    - cloud_cover
    - cloud_cover_low
    - cloud_cover_mid
    - cloud_cover_high
    - is_day
  

    

solis_data_transformation:
  root_dir: artifacts/02_intermediate
  input_file: artifacts/01_raw/solis.json 
  output_file: artifacts/02_intermediate/solis_transformed.pickle 

