artifacts_root: artifacts


# live_weather_data_ingestion:
#   root_dir: artifacts/01_raw
#   base_url: https://api.openweathermap.org/data/3.0/onecall/timemachine
#   base_url_forecast: https://api.openweathermap.org/data/3.0/onecall
#   local_data_file: artifacts/01_raw/live_weather.json
#   hours_of_history: 4
#   secret_info: config/secret_keys.yaml


# live_weather_data_transformation:
#   root_dir: artifacts/02_intermediate
#   input_file: artifacts/01_raw/live_weather.json
#   output_file_forecast: artifacts/02_intermediate/live_weather_forecast.pickle
#   output_file_actuals: artifacts/02_intermediate/live_weather_actuals.pickle
#   hours_of_forecast: 48

open_metro_API:
  root_dir: artifacts/02_intermediate
  latitude: ***REMOVED***
  longitude: ***REMOVED***
  features_minutely_15: 
    - temperature_2m
    - relative_humidity_2m
    - dew_point_2m
    - global_tilted_irradiance_instant
    - shortwave_radiation_instant
    - direct_radiation_instant 
  features_hourly: 
    - cloud_cover 
    - cloud_cover_low
    - cloud_cover_mid
    - cloud_cover_high

open_metro_hitorical:
  local_data_file_15minutely: artifacts/02_intermediate/historical_15minutely_data.pickle
  local_data_file_hourly: artifacts/02_intermediate/historical_hourly_data.pickle
  start_date: "2023-04-02"
  end_date: "2024-09-06"

open_metro_forecast: 
 local_data_file_15minutely: artifacts/02_intermediate/forecast_15minutely_data.pickle
 local_data_file_hourly: artifacts/02_intermediate/forecast_hourly_data.pickle
 past_days: 3
 forecast_days: 7


solis_data_ingestion:
  root_dir: artifacts/01_raw
  output_file: artifacts/01_raw/solis.json 
  url: 'https://www.soliscloud.com:13333'
  VERB: "POST"
  string_format: '%a, %d %b %Y %H:%M:%S GMT'
  encoder: 'utf-8'
  Content_Type: "application/json"
  CanonicalizedResource: "/v1/api/inverterDay"

solis_data_transformation:
  root_dir: artifacts/02_intermediate
  input_file: artifacts/01_raw/solis.json 
  output_file: artifacts/02_intermediate/solis_transformed.pickle 

