artifacts_root: artifacts


live_weather_data_ingestion:
  root_dir: artifacts/01_raw
  base_url: https://api.openweathermap.org/data/3.0/onecall/timemachine
  base_url_forecast: https://api.openweathermap.org/data/3.0/onecall
  local_data_file: artifacts/01_raw/live_weather.json
  hours_of_history: 4
  secret_info: config/secret_keys.yaml


live_weather_data_transformation:
  root_dir: artifacts/02_intermediate
  input_file: artifacts/01_raw/live_weather.json
  output_file_forecast: artifacts/02_intermediate/live_weather_forecast.pickle
  output_file_actuals: artifacts/02_intermediate/live_weather_actuals.pickle
  hours_of_forecast: 48

solis_data_ingestion:
  root_dir: artifacts/01_raw
  output_file: artifacts/01_raw/solis.json 
  url: 'https://www.soliscloud.com:13333'
  VERB: "POST"
  string_format: '%a, %d %b %Y %H:%M:%S GMT'
  encoder: 'utf-8'
  Content_Type: "application/json"
  CanonicalizedResource: "/v1/api/inverterDay"

solis_data_transformation:
  root_dir: artifacts/02_intermediate
  input_file: artifacts/01_raw/solis.json 
  output_file: artifacts/02_intermediate/solis_transformed.pickle 

